### ISSUE TITLE
Getting AttributeError on line 76 of graph.py: "Colors object has no attribute '%s'" % key

### ISSUE THREAD

**Issue by CodySork** [timpulver/todo.txt-graph#4]

**Comment by timpulver** [comment]
What OS and python version are you using?

**Comment by gabrielsimoes** [comment]
Also having this problem. I'm using Arch and python 3.5.1. Using 2.7.11 didn't help.

**Comment by gabrielsimoes** [comment]
Actually changing it to python2, solved, I was doing it wrong.

**Comment by timpulver** [comment]
@BrokeTheUniverse 
Can you confirm that it’s working now?
