### ISSUE TITLE
~/.todo.actions.d/graph/graph: line 19: python2: command not found

### ISSUE THREAD

**Issue by nexus-uw** [timpulver/todo.txt-graph#6]
Hi,

I installed this plugin today, and when I ran ```todo.sh graph```
I received the following error: 
```
~/.todo.actions.d/graph/graph: line 19: python2: command not found
```

My OS is OSX 10.11,
I am using zsh for my terminal shell,
and my python version is as follows
```bash
$ python
Python 2.7.10 (default, Aug 22 2015, 20:39:05)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
```

Is there some way that this plugin could be adapted for people who don't have, what I assume, multiple versions of python installed on their machines?

Thanks,
Simon

Note: changing python2 to python in _./graph_ works perfectly fine on my machine.

**Comment by timpulver** [comment]
Thanks for letting me know!

The problem is, that for a lot of people using `python` in the shebang will result in `python3` being used.

I uploaded a new version which included a check for `python2`, can you verify that it is working on your system?

**Comment by nexus-uw** [comment]
@timpulver, your fix has solved my issue. 

Thanks for the quick turn around.
